GET http://localhost:3000/products.json

###

GET http://localhost:3000/products/1.json

###

POST http://localhost:3000/products.json
Content-Type: application/json

{"name": "Moon Shoes",
  "image_url": "moonshoes.jpg",
  "price": 35,
  "description": "Bounce to da moooon!"}

###

PATCH http://localhost:3000/products/1.json
Content-Type: application/json

{"name": "Hacky Sack",
  "image_url": "chillbro.jpg",
  "price": 5,
  "description": "So chill bro...so chill"}

###
DELETE http://localhost:3000/products/4.json 

###
POST http://localhost:3000/users.json
Content-Type: application/json

{"name": "Luke Nilsson",
  "email": "luke@example.com",
  "password": "password",
  "password_confirmation": "password"
}

###

POST http://localhost:3000/sessions.json
Content-Type: application/json

{"email": "macca@example.com",
  "password": "Hofner69"
}

###
POST http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA
Content-Type: application/json

###

POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Nzg4MTY4NTF9.xaA8Ef_DEWxAOffDrTau7LuoEVlZFd4riqxw_jUK5AM
Content-Type: application/json

{
  "product_id": 1,
  "stock": 1,
  "subtotal": 1,
  "tax": 1,
  "total": 2
}

###
POST http://localhost:3000/carted_products.json
Content-Type: application/json

{"name": "Luke Nilsson",
  "email": "luke@example.com",
  "password": "password",
  "password_confirmation": "password"
}